version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${compileX_root_password}
      MYSQL_DATABASE: ${compileX_db}
      MYSQL_USER: ${test_compileX_user}
      MYSQL_PASSWORD: ${compileX_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - test_compileX_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: test_compileX_user
      PMA_PASSWORD: compileX_password
    ports:
      - "8080:80"
    networks:
      - test_compileX_network

volumes:
  mysql_data:

networks:
  test_compileX_network:
